### ISSUE TITLE
Regarding running the project

### ISSUE THREAD

**Issue by tejasruikar** [lamdav/AudioConverter#6]
Hi David, 

I emailed you last week. My question is how can I run your code. I have downloaded the code files and made necessary changes. 
Simply running python audioconverter.py isn't working, even with the command line arguments.
Sorry I am new to python and just need functionality to convert mp3 to wav mulaw.  The cli is an add on which I would like as well.
But for starters how can I run the file exactly?

Thank you,
Tejas

P.S. Just tried the updated version. It is working as intended. Do let me know how can I run the project for debugging and adding few things that I require that is logging into files so that I can use it. Thank you so much.

**Comment by lamdav** [comment]
If you just want to run it, you can use
```
pip install AudioConverter

audioconvert
```

If you are developing, you can use `poetry` tool to setup a development environment:
```shell
// create a virtualenv and spawn a shell inside virtualenv
poetry shell

// install dependencies
poetry install

// this should reference a local install of the cli. so any changes should be reflected (if not, run install again)
audioconvert
```
